### ISSUE TITLE
Error comparing int and datetime

### ISSUE THREAD

**Issue by dahlb** [dahlb/kia_uvo#39]
Logger: homeassistant.components.script.car_climate_waiting
Source: custom_components/kia_uvo/vehicle.py:148
Integration: Script (documentation, issues)
First occurred: 10:08:13 AM (2 occurrences)
Last logged: 10:08:13 AM

car: climate waiting: Repeat at step 1: Error executing script. Unexpected error for call_service at pos 2: '>' not supported between instances of 'datetime.timedelta' and 'int'
car: climate waiting: Error executing script. Unexpected error for repeat at pos 1: '>' not supported between instances of 'datetime.timedelta' and 'int'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/kia_uvo/__init__.py", line 78, in async_handle_request_sync
    await hass.async_create_task(hass_vehicle.request_sync())
  File "/config/custom_components/kia_uvo/vehicle.py", line 186, in request_sync
    await self.api_cloud.request_sync(vehicle=self)
  File "/config/custom_components/kia_uvo/api_cloud_us_kia.py", line 33, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
  File "/config/custom_components/kia_uvo/api_cloud_us_kia.py", line 279, in request_sync
    await vehicle.update()
  File "/config/custom_components/kia_uvo/vehicle.py", line 148, in update
    if age_of_last_sync > force_scan_interval:
TypeError: '>' not supported between instances of 'datetime.timedelta' and 'int'

**Comment by dahlb** [comment]
2021-12-15 09:11:59 DEBUG (MainThread) [custom_components.kia_uvo.vehicle] HVAC on, changing force_scan_interval to 5 minutes
